[workspace]
members = ["lib/*"]
resolver = "2"

[workspace.package]
edition = "2024"

[workspace.dependencies]

liquid-fixpoint = { path = "./lib/liquid-fixpoint", version = "0.1.0", features = [
    "nightly",
] }

# anstyle = "1.0.13"
# anyhow = "1.0.97"
# bumpalo = "3.17.0"
# cargo_metadata = "0.23.0"
# clap = { version = "4.5", features = ["derive"] }
# config = { version = "0.15.11", features = ["toml"], default-features = false }
# dashmap = { version = "5.5.3", features = ["raw-api"] }
# derive-where = "1.2.7"
# ena = "0.14.3"
# globset = "0.4"
# hashbrown = "0.14.5"
# home = "0.5.11"
# itertools = "0.14.0"
# pad-adapter = "0.1.1"
# rustc-hash = "2.1.1"
# serde = { version = "1.0", features = ["derive"] }
# serde_json = "1.0"
# tempfile = "3.19.1"
# toml = "0.9"
# toposort-scc = "0.5.4"

[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(flux_sysroot)',
    'cfg(flux_sysroot_test)',
    'cfg(flux)',
] }
unused_extern_crates = "warn"

[workspace.lints.rustdoc]
private_intra_doc_links = "allow"

[workspace.lints.clippy]
cloned-instead-of-copied = "warn"
disallowed-methods = "deny"
explicit-into-iter-loop = "warn"
explicit-iter-loop = "warn"
implicit-clone = "warn"
inefficient-to-string = "warn"
mismatching-type-param-order = "warn"
new-without-default = "allow"
semicolon-if-nothing-returned = "warn"

[profile.profiling]
inherits = "release"
debug = 1
